let quote=document.getElementById("quote")
let btn=document.getElementById("generate-btn")

const quotess = [
  "Push yourself, because no one else is going to do it for you.",
  "Success starts with self-discipline.",
  "Small steps every day lead to big results.",
  "Dream big. Start small. Act now.",
  "Consistency beats talent when talent doesn’t work hard.",
  "Your only limit is your mindset.",
  "Discipline is choosing what you want most over what you want now.",
  "Focus on progress, not perfection.",
  "Winners don’t quit, and quitters don’t win.",
  "Turn your pain into power.",
  "Hard work always pays off.",
  "Stay patient and trust your journey.",
  "Learn from failure and move forward.",
  "Confidence comes from preparation.",
  "Don’t watch the clock; do what it does—keep going.",
  "Action cures fear.",
  "Success is built on daily habits.",
  "Be stronger than your excuses.",
  "Growth begins outside your comfort zone.",
  "Make today count.",
  "Your future is created by what you do today.",
  "Believe in yourself even when no one else does.",
  "Discomfort is a sign of growth.",
  "Stay hungry for improvement.",
  "The best investment is in yourself.",
  "Effort is never wasted.",
  "You are capable of more than you think.",
  "Start where you are. Use what you have.",
  "Fear is temporary. Regret is forever.",
  "Build skills, not excuses.",
  "Stay focused and never settle.",
  "Every master was once a beginner.",
  "Don’t stop until you’re proud.",
  "Work hard in silence; let success make noise.",
  "Your mindset shapes your reality.",
  "Success loves preparation.",
  "Make it happen.",
  "Stay disciplined, stay unstoppable.",
  "One day or day one. You decide.",
  "Pressure creates diamonds.",
  "Chase progress, not applause.",
  "Doubt kills more dreams than failure ever will.",
  "Strive for greatness.",
  "Keep learning, keep growing.",
  "Sacrifice now, celebrate later.",
  "Push beyond your limits.",
  "Success requires sacrifice.",
  "Results demand consistency.",
  "The grind never lies.",
  "Stay committed to your goals.",
  "Dreams demand action.",
  "Be obsessed with self-improvement.",
  "Stay humble, work hard.",
  "Turn setbacks into comebacks.",
  "Discipline equals freedom.",
  "Never stop improving.",
  "Make yourself proud.",
  "Be fearless in pursuit of your goals.",
  "Create your own opportunities.",
  "Skill over luck.",
  "Outwork your past self.",
  "Stay positive, work hard.",
  "Success begins with belief.",
  "Invest in your growth.",
  "Do it now.",
  "Focus. Execute. Repeat.",
  "Stay strong during tough times.",
  "Master your habits.",
  "Think big, act bigger.",
  "Your effort defines your future.",
  "Rise above negativity.",
  "Stay committed even when it’s hard.",
  "Progress takes patience.",
  "Work until your idols become rivals.",
  "Stay consistent and unstoppable.",
  "Turn ambition into achievement.",
  "Success is earned, not given.",
  "Keep showing up.",
  "Challenge yourself daily.",
  "Never settle for average.",
  "Push harder than yesterday.",
  "Be disciplined, not motivated.",
  "Stay focused on your mission.",
  "Growth is a daily decision.",
  "Create the life you want.",
  "Hustle with purpose.",
  "Stay resilient.",
  "Effort creates opportunity.",
  "Upgrade your mindset.",
  "Be better than yesterday.",
  "Commit to excellence.",
  "Stay sharp and focused.",
  "Build your empire step by step.",
  "Stay driven.",
  "Great things take time.",
  "Make your habits work for you.",
  "Stay unstoppable.",
  "Your grind determines your glow.",
  "Level up daily."
];


btn.addEventListener("click",()=>{
    quote.innerHTML=""
    randomNum=Math.floor(Math.random()*quotess.length)
   quote.textContent=quotess[randomNum]
    
})